auto logon and start X with some ambience

diff --git a/X11/xinitrc b/X11/xinitrc
--- a/X11/xinitrc
+++ b/X11/xinitrc
@@ -3,26 +3,20 @@
 #
 # ~/.xinitrc
 #
-# Executed by startx (run your window manager from here)
-#
-# Written by Phil Muller 
 
 
 ## Ensure that the D-Bus Communication System is running properly to fix
 ## File management, authentication, and other essential system processes
-
 if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
     eval "$(dbus-launch --sh-syntax --exit-with-session)"
 fi
 
 
 ## Ensure that GTK themes are applied uniformly in the Desktop Environment
-
 export GTK2_RC_FILES="$HOME/.gtkrc-2.0" 
 
 
 ## Where the default Home folders have not already been created, generate them
-
 if [ -x /usr/bin/xdg-user-dirs-update ]; then
    /usr/bin/xdg-user-dirs-update
 fi
@@ -44,11 +38,17 @@ setxkbmap -option caps:ctrl_modifier
 # setxkbmap -option altwin:swap_alt_win
 
 # faster keyboard repeat rate
-xset r rate 180 40
+#           delay   rate
+xset r rate 200     35 
 
 [[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
 
 # thunderbolt single monitor setup
 sh ~/.screenlayout/external-single.sh 
+
+# lets wait til wireless connection comes up before launching all the apps that depend on it
+~/dotfiles/X11/wait-for-internet.sh
+[[ $? -eq 0 ]] || echo "WARNING: unable to connect to the internet"
+sleep 2
 
 exec i3
